.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2014 CAcert Software Team <software@cacert.org>,
.\"
.TH cassiopeia 1 "November 2, 2014"
.SH NAME
cassiopeia \- the CAcert.org signing software
.SH SYNOPSIS
.B cassiopeia
.RI [options]
.SH DESCRIPTION
.B cassiopeia
is the signing software that will be used to operate the CAcert.org system.
.SH OPTIONS
.TP
.B --once
Only wait for and then sign one certificate and exit instantly.
