.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2014-2017 WPIA Software Team <software@wpia.club>,
.\"
.TH cassiopeia 1 "November 2, 2014"
.SH NAME
cassiopeia \- the WPIA signing software
.SH SYNOPSIS
.B cassiopeia
.RI [options]
.SH DESCRIPTION
.B cassiopeia
is the signing software that will be used to operate the WPIA system.
.SH OPTIONS
.TP
.B --once
Only wait for and then sign one certificate and exit instantly.
